### ISSUE TITLE
windows10 下无法访问yande.re

### ISSUE THREAD

**Issue by dornenkrone** [azige/moebooru-viewer#6]
操作系统：windows 10 专业版64位1607 14393.1480
网络状态，江苏移动，yande.re被墙，konachan.com正常访问
konachan.com可以正常访问。yande.re一直卡在加载中
以下是log信息

[main] INFO io.github.azige.moebooruviewer.MoebooruViewer - init
[pool-2-thread-1] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://yande.re/post.json?api_version=2&include_pools=1&page=1&limit=100&tags=
[AWT-EventQueue-0] INFO io.github.azige.moebooruviewer.MoebooruViewer - destroy
[AWT-EventQueue-0] INFO io.github.azige.moebooruviewer.MoebooruViewer - init
[pool-3-thread-1] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/post.json?api_version=2&include_pools=1&page=1&limit=100&tags=
[pool-3-thread-2] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/0a/a3/0aa3c55c33bece478515dcfb9a4bf07f.jpg
[pool-3-thread-3] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/96/db/96dbbce8c81b87266b769a328c080a0a.jpg
[pool-3-thread-4] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/ad/f0/adf0177076322e05734dbf204c7885d0.jpg
[pool-3-thread-7] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/e0/9b/e09b25feb3b67fb391937a48479dd405.jpg
[pool-3-thread-6] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/b5/f4/b5f43529c49546ca3df729beabce608c.jpg
[pool-3-thread-5] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/62/29/6229f46a45b8dae8d58a38505f45a522.jpg
[pool-3-thread-1] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/73/56/73562c6a3cde06b00695db8c7b40981b.jpg
[pool-3-thread-8] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/01/26/012696ac522f1c0b2ff13cfc0801b85a.jpg
[pool-3-thread-10] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/96/ac/96acfa5cd6d8f3960787167d02fd0271.jpg
[pool-3-thread-9] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/preview/f5/78/f578f61d5d111307363382ac08b83e4f.jpg
[pool-3-thread-10] INFO io.github.azige.moebooruviewer.NetIO - downloaded: Konachan.net\previews\249857.jpg
[pool-3-thread-10] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/data/pre[pool-2-thread-1] INFO io.github.azige.moebooruviewer.NetIO - IO异常，重试
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.fastRead(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:459)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2431)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2411)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:285)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:233)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:270)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2202)
	at io.github.azige.moebooruviewer.MoebooruAPI.listPosts(MoebooruAPI.java:74)
	at io.github.azige.moebooruviewer.ListPostFrame.lambda$null$1(ListPostFrame.java:165)
	at io.github.azige.moebooruviewer.NetIO.retry(NetIO.java:98)
	at io.github.azige.moebooruviewer.ListPostFrame.lambda$loadImages$3(ListPostFrame.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[pool-2-thread-1] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://yande.re/post.json?api_version=2&include_pools=1&page=1&limit=100&tags=
[pool-2-thread-1] INFO io.github.azige.moebooruviewer.NetIO - IO异常，重试
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.fastRead(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:459)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2431)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2411)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:285)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:233)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:270)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2202)
	at io.github.azige.moebooruviewer.MoebooruAPI.listPosts(MoebooruAPI.java:74)
	at io.github.azige.moebooruviewer.ListPostFrame.lambda$null$1(ListPostFrame.java:165)
	at io.github.azige.moebooruviewer.NetIO.retry(NetIO.java:98)
	at io.github.azige.moebooruviewer.ListPostFrame.lambda$loadImages$3(ListPostFrame.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
[pool-2-thread-1] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://yande.re/post.json?api_version=2&include_pools=1&page=1&limit=100&tags=
[pool-2-thread-1] INFO io.github.azige.moebooruviewer.NetIO - IO异常，重试
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at sun.security.ssl.InputRecord.readFully(Unknown Source)
	at sun.security.ssl.InputRecord.readV3Record(Unknown Source)
	at sun.security.ssl.InputRecord.read(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
	at sun.security.ssl.AppInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read1(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.fastRead(Unknown Source)
	at sun.net.www.http.ChunkedInputStream.read(Unknown Source)
	at java.io.FilterInputStream.read(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(Unknown Source)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.loadMore(UTF8StreamJsonParser.java:180)
	at com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:459)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2431)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2411)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:285)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:233)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:270)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:69)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:15)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3702)
	at com.fasterxml.jackson.da[pool-3-thread-10] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/jpeg/1b9e8cec843e6bd337f4b5a19af85515/Konachan.com%20-%20249833%20boots%20brown_hair%20cape%20gloves%20male%20pantyhose%20ruby_rose%20rwby%20scarf%20short_hair%20snow%20tagme_%28character%29%20tree%20truc_bui%20winter.jpg
[pool-3-thread-6] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/tag.json?name=truc_bui
[pool-3-thread-2] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/jpeg/d4d4977a3ac0e873de4e3df2a89d4095/Konachan.com%20-%20249832%20close%20memento_%28sennen_sensou_aigis%29%20navel%20sennen_sensou_aigis%20tattoo%20thighhighs%20toriniku_%28selene1050%29.jpg
[pool-3-thread-5] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/tag.json?name=memento_(sennen_sensou_aigis)
[pool-3-thread-5] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/tag.json?name=sennen_sensou_aigis
[pool-3-thread-5] INFO io.github.azige.moebooruviewer.NetIO - downloading: https://konachan.net/tag.json?name=toriniku_(selene1050)
[pool-3-thread-10] INFO io.github.azige.moebooruviewer.NetIO - downloaded: Konachan.net\samples\249833.jpg
[pool-3-thread-2] INFO io.github.azige.moebooruviewer.NetIO - downloaded: Konachan.net\samples\249832.jpg
[AWT-EventQueue-0] INFO io.github.azige.moebooruviewer.MoebooruViewer - destroy
ch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by azige** [comment]
可以尝试一下用浏览器直接访问 https://yande.re/
个人试了一下貌似目前暂时没被墙，只是速度很慢。现在程序里设置的超时是30秒，可能慢到已经超过30秒所以失败了。

**Comment by dornenkrone** [comment]
嗯嗯  好的 谢谢大大
